// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.DAL.DBContexts;

namespace POS.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180727232800_TestDB")]
    partial class TestDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("POS.DAL.Models.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("BuyingPrice");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("Name");

                    b.Property<float?>("SellingPrice");

                    b.Property<float?>("SpeacialSellingPrice");

                    b.Property<int?>("Unit");

                    b.HasKey("Id");

                    b.ToTable("Pricings");
                });

            modelBuilder.Entity("POS.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("EnterDate");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<int?>("PricingId");

                    b.HasKey("Id");

                    b.HasIndex("PricingId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("POS.DAL.Models.Product", b =>
                {
                    b.HasOne("POS.DAL.Models.Pricing", "Pricing")
                        .WithMany("Products")
                        .HasForeignKey("PricingId");
                });
#pragma warning restore 612, 618
        }
    }
}
